function getDatasetDescription(datasetName) {
    const datasetDescriptions = {
        "weather": "Weather is recorded every 10 minutes for the 2020 whole year, which contains 21 meteorological indicators, such as air temperature, humidity, etc.",
        "traffic": "Traffic is a collection of hourly data from California Department of Transportation, which describes the road occupancy rates measured by different sensors on San Francisco Bay area freeways.",
        "solar":"The Solar Power Data for Integration Studies consist of 1 year (2006) of 5-minute solar power and hourly day-ahead forecasts for approximately 6,000 simulated PV plants.",
        "wind":"This dataset contains a single very long daily time series representing the wind power production in MW recorded per every 4 seconds starting from 01/08/2019. It was downloaded from the Australian Energy Market Operator (AEMO) online platform. The length of this time series is 7397147.",
        "electricity":"This data set contains electricity consumption of 370 points/clients. Values are in kW of each 15 min. All time labels report to Portuguese hour. However, all days present 96 measures (24*4). ",
        "taxi":"The Taxi Dataset includes millions of individual trip records spanning a period of several years, from 2009 to the present. Each entry includes timestamps for pickup and drop-off, coordinates of pickup/drop-off locations, fare amount, tip amount, payment type, and distance traveled. ",
        "pedestrian":"This dataset contains hourly pedestrian counts captured from 66 sensors in Melbourne city starting from May 2009.",
        "air":"The Air Dataset contains hourly measurements of air pollutant concentrations and meteorological data collected from multiple monitoring stations within a city or region.  This archive contains millions of records collected continuously over a span of more than 20 years, from 2000 to the present. ",
        "temperature":"The Temperature Dataset contains daily temperature measurements recorded across multiple weather stations in a specific region. This archive consists of millions of observations collected over a period of more than 50 years, spanning from 1970 to the present. Each record includes the date, location of the weather station, and the respective temperature readings. ",
        "rain":"This dataset contains 32072 daily time series showing the temperature observations and rain forecasts, gathered by the Australian Bureau of Meteorology for 422 weather stations across Australia, between 02/05/2015 and 26/04/2017.",
        "nn5":"This dataset was used in the NN5 forecasting competition. It contains 111 time series from the banking domain. The goal is predicting the daily cash withdrawals from ATMs in UK.",
        "fred":"The FRED-MD dataset contains monthly macroeconomic indicators from the United States, spanning a period of over 60 years. A wide range of economic categories is represented, including real output, income, labor markets, housing, inflation, interest rates, and stock markets. The dataset includes 637,965 observations, collected from various government and financial institutions across the U.S., and is updated on a monthly basis.",
        "exchange":"This dataset contains official exchange rates of various currencies against a base currency, as reported by the respective central banks or other official sources. The dataset includes daily exchange rates for a period of 2020 - 2023.",
        "m4":"The M4 dataset is a collection of 100,000 time series used for the fourth edition of the Makridakis forecasting Competition. The M4 dataset consists of time series of yearly, quarterly, monthly and other (weekly, daily and hourly) data, which are divided into training and test sets. The minimum numbers of observations in the training test are 13 for yearly, 16 for quarterly, 42 for monthly, 80 for weekly, 93 for daily and 700 for hourly series. The participants were asked to produce the following numbers of forecasts beyond the available data that they had been given: six for yearly, eight for quarterly, 18 for monthly series, 13 for weekly series and 14 and 48 forecasts respectively for the daily and hourly ones.",
        "illiness":"The Illness Dataset contains daily records of reported illness cases across multiple healthcare facilities in a specific region. This archive comprises hundreds of thousands of entries collected over a period of 10 years, from 2010 to the present. ",
    };
    return datasetDescriptions[datasetName] || "the prompt description for each of dataset.";
}